//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LZY.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class t_para_values
    {
        public int p_id { get; set; }
        public bool p_deleted { get; set; } = false;
        [Required, StringLength(maximumLength: 50)]
        public string p_value { get; set; }
        [Required, Range(0, 888)]
        public Nullable<int> p_sort { get; set; } = 888;
        public Nullable<System.DateTime> p_createtime { get; set; }
        public Nullable<int> p_createuserid { get; set; }
        public Nullable<System.DateTime> p_updatetime { get; set; }
        public Nullable<int> p_updateuserid { get; set; }
        [StringLength(maximumLength: 50)]

        public string p_attribute1 { get; set; }
        [StringLength(maximumLength: 50)]

        public string p_attribute2 { get; set; }
        [StringLength(maximumLength: 50)]

        public string p_attribute3 { get; set; }
        public Nullable<int> p_attribute4 { get; set; }
        public Nullable<decimal> p_attribute5 { get; set; }
        public Nullable<System.DateTime> p_attribute6 { get; set; }
        [Required]

        public int p_pid { get; set; }

        [Required]
        [StringLength(maximumLength: 20, MinimumLength = 3)]
        public string p_code { get; set; }
    }
}
