//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LZY.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_syslog
    {
        public int p_id { get; set; }
        public int p_type { get; set; }
        public string p_content { get; set; }
        public Nullable<System.DateTime> p_createtime { get; set; }
        public Nullable<int> p_createuserid { get; set; }
        public string p_attribute1 { get; set; }
        public string p_attribute2 { get; set; }
        public string p_attribute3 { get; set; }
    }
}
